name: Capstone-Chicago
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- _license=1.1=py35_1
- anaconda=custom=py35_0
- anaconda-navigator=1.3.2=py35_0
- appscript=1.0.1=py35_0
- backports=1.0=py35_0
- bitarray=0.8.1=py35_0
- blaze=0.10.1=py35_0
- bokeh=0.12.4=py35_0
- boto=2.45.0=py35_0
- chest=0.2.3=py35_0
- conda-forge::alabaster=0.7.10=py35_0
- conda-forge::anaconda-client=1.5.1=py35_0
- conda-forge::appnope=0.1.0=py35_0
- conda-forge::astroid=1.4.8=py35_0
- conda-forge::astropy=1.3=np112py35_0
- conda-forge::babel=2.3.4=py35_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py35_1
- conda-forge::beautifulsoup4=4.5.3=py35_0
- conda-forge::bleach=1.5.0=py35_0
- conda-forge::bottleneck=1.2.0=np112py35_0
- conda-forge::certifi=2017.1.23=py35_0
- conda-forge::cffi=1.7.0=py35_0
- conda-forge::chardet=2.3.0=py35_0
- conda-forge::click=6.7=py35_0
- conda-forge::cloudpickle=0.2.2=py35_2
- conda-forge::clyent=1.2.1=py35_0
- conda-forge::colorama=0.3.7=py35_0
- conda-forge::contextlib2=0.5.4=py35_0
- conda-forge::coverage=4.3.4=py35_0
- conda-forge::curl=7.52.1=0
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::cython=0.25.2=py35_0
- conda-forge::cytoolz=0.8.2=py35_0
- conda-forge::dask=0.13.0=py35_0
- conda-forge::decorator=4.0.11=py35_0
- conda-forge::dill=0.2.6=py35_0
- conda-forge::docutils=0.13.1=py35_0
- conda-forge::entrypoints=0.2.2=py35_1
- conda-forge::flask=0.12=py35_0
- conda-forge::flask-cors=3.0.2=py35_0
- conda-forge::h5py=2.6.0=np112py35_7
- conda-forge::heapdict=1.0.0=py35_0
- conda-forge::html5lib=0.999=py35_0
- conda-forge::idna=2.1=py35_0
- conda-forge::imagesize=0.7.1=py35_0
- conda-forge::ipykernel=4.5.2=py35_0
- conda-forge::ipython=5.3.0=py35_0
- conda-forge::ipython_genutils=0.1.0=py35_0
- conda-forge::ipywidgets=6.0.0=py35_0
- conda-forge::isort=4.2.5=py35_0
- conda-forge::itsdangerous=0.24=py35_1
- conda-forge::jedi=0.10.0=py35_0
- conda-forge::jinja2=2.9.5=py35_0
- conda-forge::jpeg=9b=0
- conda-forge::jsonschema=2.5.1=py35_0
- conda-forge::jupyter=1.0.0=py35_0
- conda-forge::jupyter_client=5.0.0=py35_0
- conda-forge::jupyter_console=5.1.0=py35_0
- conda-forge::jupyter_core=4.3.0=py35_0
- conda-forge::lazy-object-proxy=1.2.2=py35_0
- conda-forge::libffi=3.2.1=3
- conda-forge::libiconv=1.14=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::libxslt=1.1.29=0
- conda-forge::locket=0.2.0=py35_1
- conda-forge::lxml=3.7.3=py35_0
- conda-forge::markupsafe=0.23=py35_1
- conda-forge::mccabe=0.6.1=py35_0
- conda-forge::mistune=0.7.3=py35_1
- conda-forge::mpmath=0.19=py35_2
- conda-forge::multipledispatch=0.4.9=py35_0
- conda-forge::nbconvert=5.1.1=py35_0
- conda-forge::nbformat=4.2.0=py35_0
- conda-forge::networkx=1.11=py35_0
- conda-forge::nltk=3.2.2=py35_0
- conda-forge::nose=1.3.7=py35_2
- conda-forge::notebook=4.4.1=py35_0
- conda-forge::numexpr=2.6.2=np112py35_0
- conda-forge::numpydoc=0.6.0=py35_0
- conda-forge::pandas=0.19.2=np112py35_1
- conda-forge::pandoc=1.19.2=0
- conda-forge::pandocfilters=1.4.1=py35_0
- conda-forge::partd=0.3.7=py35_0
- conda-forge::path.py=8.2.1=py35_0
- conda-forge::pathlib2=2.2.1=py35_0
- conda-forge::patsy=0.4.1=py35_0
- conda-forge::pep8=1.7.0=py35_0
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pillow=3.2.0=py35_1
- conda-forge::pip=9.0.1=py35_0
- conda-forge::ply=3.9=py35_0
- conda-forge::prompt_toolkit=1.0.13=py35_0
- conda-forge::psutil=5.1.3=py35_0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::py=1.4.31=py35_0
- conda-forge::pyasn1=0.2.2=py35_0
- conda-forge::pycosat=0.6.1=py35_0
- conda-forge::pycparser=2.17=py35_0
- conda-forge::pycrypto=2.6.1=py35_0
- conda-forge::pyflakes=1.5.0=py35_0
- conda-forge::pygments=2.2.0=py35_0
- conda-forge::pylint=1.6.4=py35_0
- conda-forge::pyopenssl=16.2.0=py35_0
- conda-forge::pyparsing=2.1.10=py35_0
- conda-forge::pytables=3.3.0=np112py35_0
- conda-forge::pytest=3.0.6=py35_0
- conda-forge::python=3.5.3=1
- conda-forge::python-dateutil=2.6.0=py35_0
- conda-forge::pytz=2016.10=py35_0
- conda-forge::pyyaml=3.12=py35_0
- conda-forge::pyzmq=16.0.2=py35_0
- conda-forge::qtawesome=0.4.4=py35_0
- conda-forge::qtconsole=4.2.1=py35_0
- conda-forge::qtpy=1.2.1=py35_0
- conda-forge::redis-py=2.10.5=py35_0
- conda-forge::requests=2.13.0=py35_0
- conda-forge::scikit-image=0.12.3=np112py35_1
- conda-forge::seaborn=0.7.1=py35_0
- conda-forge::setuptools=33.1.0=py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::singledispatch=3.4.0.3=py35_0
- conda-forge::sip=4.18=py35_1
- conda-forge::six=1.10.0=py35_1
- conda-forge::snowballstemmer=1.2.1=py35_0
- conda-forge::sphinx=1.5.2=py35_0
- conda-forge::spyder=2.3.9=py35_1
- conda-forge::sqlalchemy=1.1.5=py35_0
- conda-forge::sqlite=3.13.0=0
- conda-forge::statsmodels=0.8.0=np112py35_0
- conda-forge::sympy=1.0=py35_0
- conda-forge::terminado=0.6=py35_0
- conda-forge::testpath=0.3=py35_0
- conda-forge::toolz=0.8.2=py35_0
- conda-forge::tornado=4.4.2=py35_0
- conda-forge::traitlets=4.3.1=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::webencodings=0.5=py35_0
- conda-forge::werkzeug=0.11.10=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::widgetsnbextension=2.0.0=py35_0
- conda-forge::wrapt=1.10.8=py35_0
- conda-forge::xlrd=1.0.0=py35_1
- conda-forge::yaml=0.1.6=0
- conda-forge::zeromq=4.1.5=0
- conda-forge::zlib=1.2.8=3
- configobj=5.0.6=py35_0
- cryptography=1.7.1=py35_0
- datashape=0.5.4=py35_0
- et_xmlfile=1.0.1=py35_0
- fastcache=1.0.2=py35_1
- freetype=2.5.5=2
- get_terminal_size=1.0.0=py35_0
- gevent=1.2.1=py35_0
- greenlet=0.4.12=py35_0
- hdf5=1.8.17=1
- icu=54.1=0
- jbig=2.1=0
- jdcal=1.3=py35_0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- llvmlite=0.16.0=py35_0
- matplotlib=2.0.0=np112py35_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py35_3
- numba=0.31.0=np112py35_0
- numpy=1.12.0=py35_0
- odo=0.5.0=py35_1
- openpyxl=2.4.1=py35_0
- openssl=1.0.2k=0
- pycurl=7.43.0=py35_2
- pyqt=5.6.0=py35_2
- python.app=1.2=py35_4
- qt=5.6.2=0
- readline=6.2=2
- redis=3.2.0=0
- rope=0.9.4=py35_1
- scikit-learn=0.18.1=np112py35_1
- scipy=0.18.1=np112py35_1
- sockjs-tornado=1.0.3=py35_0
- tk=8.5.18=0
- unicodecsv=0.14.1=py35_0
- xlsxwriter=0.9.6=py35_0
- xlwings=0.10.2=py35_0
- xlwt=1.2.0=py35_0
- xz=5.2.2=1
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - et-xmlfile==1.0.1
  - ipython-genutils==0.1.0
  - jupyter-client==5.0.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.13
  - rope-py3k==0.9.4.post1
  - tables==3.3.0

